FROM python:3.14.6-slim

RUN useradd --create-home --shell /bin/bash app
WORKDIR /app

COPY Swarm_Repo/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY wfc_shared /wfc_shared
RUN pip install -e /wfc_shared

COPY ./Swarm_Repo .

USER app

CMD ["python", "main_scout.py"]
